version: '3.8'

services:
  app:
    container_name: erp-frontend-dev
    image: mz-erp-frontend-dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    environment:
      PORT: 5173